# Change these first
owner:  HS-Scene-Admin  # Your GitHub organization or username, where this repository lives
repo: hs-scene-status # The name of this repository

sites:
  - name: HS-Scene.to
    url: https://www.hs-scene.to/status.php
    icon: https://raw.githubusercontent.com/HS-Scene-Admin/hs-scene-status/master/assets/favicon.gif

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hs-scene.to
  # baseUrl: /
  logoUrl: https://raw.githubusercontent.com/HS-Scene-Admin/hs-scene-status/master/assets/pageLogo-350.png
  name: HS-Scene Status
  introTitle: "**HS-Scene** Status Info."
  introMessage: "Hier kannst du den aktuellen Status unseres Forums sehen"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
